version: '3.4'

services:
  api70.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api70api
    build:
      context: .
      dockerfile: src/Api70.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__Host: rabbitMQ
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__UseSsl: 'false'
      RabbitMQ__VirtualHost: /
      RabbitMQ__RetryCount: 5
      RabbitMQ__ClientName: api70
    ports:
      - 5001:443
      - 5000:80
    depends_on:
      - rabbitMQ
  
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - 5340:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
  
  rabbitMQ:
    container_name: rabbitMQ
    ports:
      - "15672:15672"
      - "15692:15692" #prometheus metrics
      - "5672:5672"
    image: "rabbitmq:3.11.8-management-alpine"
    healthcheck:
      timeout: 15s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
  
  locust:
    container_name: master
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust:8089
  
  worker:
    container_name: worker
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust